import { ref } from 'vue'
const cities = ref([
  'Aceh',
  'Kab. Aceh Barat, Aceh',
  'Kab. Aceh Barat Daya, Aceh',
  'Kab. Aceh Besar, Aceh',
  'Kab. Aceh Jaya, Aceh',
  'Kab. Aceh Selatan, Aceh',
  'Kab. Aceh Singkil, Aceh',
  'Kab. Aceh Tamiang, Aceh',
  'Kab. Aceh Tengah, Aceh',
  'Kab. Aceh Tenggara, Aceh',
  'Kab. Aceh Timur, Aceh',
  'Kab. Aceh Utara, Aceh',
  'Kab. Bener Meriah, Aceh',
  'Kab. Biruen, Aceh',
  'Kab. Gayo Lues, Aceh',
  'Kab. Nagan Raya, Aceh',
  'Kab. Pidie, Aceh',
  'Kab. Pidie Jaya, Aceh',
  'Kab. Simeulue, Aceh',
  'Banda Aceh',
  'Langsa, Aceh',
  'Lhokseumawe, Aceh',
  'Sabang, Aceh',
  'Subulussalam, Aceh',
  'Sumatra Utara',
  'Kab. Asahan, Sumatra Utara',
  'Kab. Batu Bara, Sumatra Utara',
  'Kab. Dairi, Sumatra Utara',
  'Kab. Deli Serdang, Sumatra Utara',
  'Kab. Humbang Hasundutan, Sumatra Utara',
  'Kab. Karo, Sumatra Utara',
  'Kab. Labuhanbatu, Sumatra Utara',
  'Kab. Labuhanbatu Selatan, Sumatra Utara',
  'Kab. Labuhanbatu Utara, Sumatra Utara',
  'Kab. Langkat, Sumatra Utara',
  'Kab. Mandailing Natal, Sumatra Utara',
  'Kab. Nias, Sumatra Utara',
  'Kab. Nias Barat, Sumatra Utara',
  'Kab. Nias Selatan, Sumatra Utara',
  'Kab. Nias Utara, Sumatra Utara',
  'Kab. Padang Lawas, Sumatra Utara',
  'Kab. Padang Lawas Utara, Sumatra Utara',
  'Kab. Pakpak Bharat, Sumatra Utara',
  'Kab. Samosir, Sumatra Utara',
  'Kab. Serdang Bedagai, Sumatra Utara',
  'Kab. Simalungun, Sumatra Utara',
  'Kab. Tapanuli Selatan, Sumatra Utara',
  'Kab. Tapanuli Tengah, Sumatra Utara',
  'Kab. Tapanuli Utara, Sumatra Utara',
  'Kab. Toba, Sumatra Utara',
  'Binjai, Sumatra Utara',
  'Gunungsitoli, Sumatra Utara',
  'Medan, Sumatra Utara',
  'Padang Sidempuan, Sumatra Utara',
  'Pematang Siantar, Sumatra Utara',
  'Sibolga, Sumatra Utara',
  'Tanjungbalai, Sumatra Utara',
  'Tebing Tinggi, Sumatra Utara',
  'Sumatra Barat',
  'Kab. Agam, Sumatra Barat',
  'Kab. Dharmasraya, Sumatra Barat',
  'Kab. Kepulauan Mentawai, Sumatra Barat',
  'Kab. Lima Puluh Kota, Sumatra Barat',
  'Kab. Padang Pariaman, Sumatra Barat',
  'Kab. Pasaman, Sumatra Barat',
  'Kab. Pasaman Barat, Sumatra Barat',
  'Kab. Pesisir Selatan, Sumatra Barat',
  'Kab. Sijunjung, Sumatra Barat',
  'Kab. Solok, Sumatra Barat',
  'Kab. Tanah Datar, Sumatra Barat',
  'Bukit Tinggi, Sumatra Barat',
  'Padang, Sumatra Barat',
  'Padang Panjang, Sumatra Barat',
  'Pariaman, Sumatra Barat',
  'Payukumbuh, Sumatra Barat',
  'Sawahlunto, Sumatra Barat',
  'Kota Solok, Sumatra Barat',
  'Riau',
  'Kab. Bengkalis, Riau',
  'Kab. Indragiri Hilir, Riau',
  'Kab. Indragiri Hulu, Riau',
  'Kab. Kampar, Riau',
  'Kab. Kepulauan Meranti, Riau',
  'Kab. Kuantan Singingi, Riau',
  'Kab. Pelalawan, Riau',
  'Kab. Rokan Hilir, Riau',
  'Kab. Rokan Hulu, Riau',
  'Kab. Siak, Riau',
  'Dumai, Riau',
  'Pekanbaru, Riau',
  'Kepulauan Riau',
  'Kab. Bintan, Kepulauan Riau',
  'Kab. Karimun, Kepulauan Riau',
  'Kab. Kepulauan Anambas, Kepulauan Riau',
  'Kab. Lingga, Kepulauan Riau',
  'Kab. Natuna, Kepulauan Riau',
  'Batam, Kepulauan Riau',
  'Tanjung Pinang, Kepulauan Riau',
  'Jambi',
  'Kab. Batanghari, Jambi',
  'Kab. Bungo, Jambi',
  'Kab. Kerinci, Jambi',
  'Kab. Merangin, Jambi',
  'Kab. Muaro Jambi, Jambi',
  'Kab. Sarolangun, Jambi',
  'Kab. Tanjung Jambung Barat, Jambi',
  'Kab. Tanjung Jambung Timur, Jambi',
  'Kab. Tebo, Jambi',
  'Kota Jambi',
  'Sungai Penuh, Jambi',
  'Bengkulu',
  'Kab. Bengkulu Selatan',
  'Kab. Bengkulu Tengah',
  'Kab. Bengkulu Utara',
  'Kab. Kaur, Bengkulu',
  'Kab. Kepahiang, Bengkulu',
  'Kab. Lebong, Bengkulu',
  'Kab. Mukomuko, Bengkulu',
  'Kab. Rejang Lebong, Bengkulu',
  'Kab. Seluma, Bengkulu',
  'Kota Bengkulu',
  'Sumatra Selatan',
  'Kab. Banyuasin, Sumatra Selatan',
  'Kab. Empat Lawang, Sumatra Selatan',
  'Kab. Lahat, Sumatra Selatan',
  'Kab. Muara Enim, Sumatra Selatan',
  'Kab. Musi Banyuasin, Sumatra Selatan',
  'Kab. Musi Rawas, Sumatra Selatan',
  'Kab. Musi Rawas Utara, Sumatra Selatan',
  'Kab. Ogan lir, Sumatra Selatan',
  'Kab. Ogan Komering Ilir, Sumatra Selatan',
  'Kab. Ogan Komering Ulu, Sumatra Selatan',
  'Kab. Ogan Komering Ulu Selatan, Sumatra Selatan',
  'Kab. Ogan Komering Ulu Timur, Sumatra Selatan',
  'Kab. Penukang Abab Pematang Ilir, Sumatra Selatan',
  'Lubuklinggau, Sumatra Selatan',
  'Pagar Alam, Sumatra Selatan',
  'Palembang, Sumatra Selatan',
  'Prabumulih, Sumatra Selatan',
  'Kepulauan Bangka Belitung',
  'Kab. Bangka, Kepulauan Bangka Belitung',
  'Kab. Bangka Barat, Kepulauan Bangka Belitung',
  'Kab. Bangka Selatan, Kepulauan Bangka Belitung',
  'Kab. Bangka Tengah, Kepulauan Bangka Belitung',
  'Kab. Belitung, Kepulauan Bangka Belitung',
  'Kab. Belitung Timur, Kepulauan Bangka Belitung',
  'Pangkal Pinang, Kepulauan Bangka Belitung',
  'Lampung',
  'Kab. Lampung Barat',
  'Kab. Lampung Selatan',
  'Kab. Lampung Tengah',
  'Kab. Lampung Timur',
  'Kab. Lampung Utara',
  'Kab. Mesuji, Lampung',
  'Kab. Pesawaran, Lampung',
  'Kab. Pesisir Barat, Lampung',
  'Kab. Pringsewu, Lampung',
  'Kab. Tanggamus, Lampung',
  'Kab. Tulang Bawang, Lampung',
  'Kab. Tulang Bawang Barat, Lampung',
  'Kab. Way Kanan, Lampung',
  'Bandar Lampung, Lampung',
  'Metro, Lampung',
  'Banten',
  'Kab. Lebak, Banten',
  'Kab. Pandeglang, Banten',
  'Kab. Serang, Banten',
  'Kab. Tangerang, Banten',
  'Cilegon, Banten',
  'Serang, Banten',
  'Kota Tangerang, Banten',
  'Kota Tangerang Selatan, Banten',
  'Jawa Barat',
  'Kab. Bandung, Jawa Barat',
  'Kab. Bandung Barat, Jawa Barat',
  'Kab. Bekasi, Jawa Barat',
  'Kab. Bogor, Jawa Barat',
  'Kab. Ciamis, Jawa Barat',
  'Kab. Cianjur, Jawa Barat',
  'Kab. Cirebon, Jawa Barat',
  'Kab. Garut, Jawa Barat',
  'Kab. Indramayu, Jawa Barat',
  'Kab. Karawang, Jawa Barat',
  'Kab. Kuningan, Jawa Barat',
  'Kab. Majalengka, Jawa Barat',
  'Kab. Pangandaran, Jawa Barat',
  'Kab. Purwakarta, Jawa Barat',
  'Kab. Subang, Jawa Barat',
  'Kab. Sukabumi, Jawa Barat',
  'Kab. Sumedang, Jawa Barat',
  'Kab. Tasikmalaya, Jawa Barat',
  'Kota Bandung, Jawa Barat',
  'Banjar, Jawa Barat',
  'Kota Bekasi, Jawa Barat',
  'Kota Bogor, Jawa Barat',
  'Cimahi, Jawa Barat',
  'Kota Cirebon, Jawa Barat',
  'Depok, Jawa Barat',
  'Sukabumi, Jawa Barat',
  'Kota Tasikmalaya, Jawa Barat',
  'DKI Jakarta',
  'Jakarta Barat, DKI Jakarta',
  'Jakarta Pusat, DKI Jakarta',
  'Jakarta Selatan, DKI Jakarta',
  'Jakarta Timur, DKI Jakarta',
  'Jakarta Utara, DKI Jakarta',
  'Jawa Tengah',
  'Kab. Banjarnegara, Jawa Tengah',
  'Kab. Banyumas, Jawa Tengah',
  'Kab. Batang, Jawa Tengah',
  'Kab. Blora, Jawa Tengah',
  'Kab. Boyolali, Jawa Tengah',
  'Kab. Brebes, Jawa Tengah',
  'Kab. Cilacap, Jawa Tengah',
  'Kab. Demak, Jawa Tengah',
  'Kab. Grobogan, Jawa Tengah',
  'Kab. Jepara, Jawa Tengah',
  'Kab. Karanganyar, Jawa Tengah',
  'Kab. Kebumen, Jawa Tengah',
  'Kab. Kendal, Jawa Tengah',
  'Kab. Klaten, Jawa Tengah',
  'Kab. Kudus, Jawa Tengah',
  'Kab. Magelang, Jawa Tengah',
  'Kab. Pati, Jawa Tengah',
  'Kab. Pekalongan, Jawa Tengah',
  'Kab. Pemalang, Jawa Tengah',
  'Kab. Purbalingga, Jawa Tengah',
  'Kab. Purworejo, Jawa Tengah',
  'Kab. Rembang, Jawa Tengah',
  'Kab. Semarang, Jawa Tengah',
  'Kab. Sragen, Jawa Tengah',
  'Kab. Sukoharjo, Jawa Tengah',
  'Kab. Tegal, Jawa Tengah',
  'Kab. Temanggung, Jawa Tengah',
  'Kab. Wonogiri, Jawa Tengah',
  'Kab. Wonosobo, Jawa Tengah',
  'Kota Magelang, Jawa Tengah',
  'Kota Pekalongan, Jawa Tengah',
  'Salatiga, Jawa Tengah',
  'Kota Semarang, Jawa Tengah',
  'Surakarta, Jawa Tengah',
  'Kota Tegal, Jawa Tengah',
  'D.I. Yogyakarta',
  'Kab. Bantul, DIY',
  'Kab. Gunungkidul, DIY',
  'Kab. Kulon Progo, DIY',
  'Kab. Sleman, DIY',
  'Yogyakarta, DIY',
  'Jawa Timur',
  'Kab. Bangkalan, Jawa Timur',
  'Kab. Banyuwangi, Jawa Timur',
  'Kab. Blitar, Jawa Timur',
  'Kab. Bojonegoro, Jawa Timur',
  'Kab. Bondowoso, Jawa Timur',
  'Kab. Gresik, Jawa Timur',
  'Kab. Jember, Jawa Timur',
  'Kab. Jombang, Jawa Timur',
  'Kab. Kediri, Jawa Timur',
  'Kab. Lamongan, Jawa Timur',
  'Kab. Lumajang, Jawa Timur',
  'Kab. Madiun, Jawa Timur',
  'Kab. Magetan, Jawa Timur',
  'Kab. Malang, Jawa Timur',
  'Kab. Mojokerto, Jawa Timur',
  'Kab. Nganjuk, Jawa Timur',
  'Kab. Ngawi, Jawa Timur',
  'Kab. Pacitan, Jawa Timur',
  'Kab. Pamekasan, Jawa Timur',
  'Kab. Pasuruan, Jawa Timur',
  'Kab. Ponorogo, Jawa Timur',
  'Kab. Probolinggo, Jawa Timur',
  'Kab. Sampang, Jawa Timur',
  'Kab. Sidoarjo, Jawa Timur',
  'Kab. Situbondo, Jawa Timur',
  'Kab. Sumenep, Jawa Timur',
  'Kab. Trenggalek, Jawa Timur',
  'Kab. Tuban, Jawa Timur',
  'Kab. Tulungagung, Jawa Timur',
  'Batu, Jawa Timur',
  'Kota Blitar, Jawa Timur',
  'Kota Kediri, Jawa Timur',
  'Kota Madiun, Jawa Timur',
  'Kota Malang, Jawa Timur',
  'Kota Mojokerto, Jawa Timur',
  'Kota Pasuruan, Jawa Timur',
  'Kota Probolinggo, Jawa Timur',
  'Surabaya, Jawa Timur',
  'Bali',
  'Kab. Badung, Bali',
  'Kab. Bangli, Bali',
  'Kab. Buleleng, Bali',
  'Kab. Gianyar, Bali',
  'Kab. Jembrana, Bali',
  'Kab. Karangasem, Bali',
  'Kab. Klungkung, Bali',
  'Kab. Tabanan, Bali',
  'Denpasar, Bali',
  'Nusa Tenggara Barat',
  'Kab. Bima, Nusa Tenggara Barat',
  'Kab. Dompu, Nusa Tenggara Barat',
  'Kab. Lombok Barat, Nusa Tenggara Barat',
  'Kab. Lombok Tengah, Nusa Tenggara Barat',
  'Kab. Lombook Timur, Nusa Tenggara Barat',
  'Kab. Lombok Utara, Nusa Tenggara Barat',
  'Kab. Sumbawa, Nusa Tenggara Barat',
  'Kab. Sumbawa Barat, Nusa Tenggara Barat',
  'Kota Bima, Nusa Tenggara Barat',
  'Mataram, Nusa Tenggara Barat',
  'Nusa Tenggara Timur',
  'Kab. Alon, Nusa Tenggara Timur',
  'Kab. Belu, Nusa Tenggara Timur',
  'Kab. Ende, Nusa Tenggara Timur',
  'Kab. Flores timur, Nusa Tenggara Timur',
  'Kab. Kupang, Nusa Tenggara Timur',
  'Kab. Lembata, Nusa Tenggara Timur',
  'Kab. Malaka, Nusa Tenggara Timur',
  'Kab. Manggara, Nusa Tenggara Timur',
  'Kab. Manggarai Barat, Nusa Tenggara Timur',
  'Kab. Manggarai Timur, Nusa Tenggara Timur',
  'Kab. Nagekeo, Nusa Tenggara Timur',
  'Kab. Ngada, Nusa Tenggara Timur',
  'Kab. Rote Ndao, Nusa Tenggara Timur',
  'Kab. Sabu Raijua, Nusa Tenggara Timur',
  'Kab. Sikka, Nusa Tenggara Timur',
  'Kab. Sumba Barat, Nusa Tenggara Timur',
  'Kab. Sumba Barat Daya, Nusa Tenggara Timur',
  'Kab. Sumba Tengah, Nusa Tenggara Timur',
  'Kab. Sumba Timur, Nusa Tenggara Timur',
  'Kab. Timor Tenga Selatan, Nusa Tenggara Timur',
  'Kab. Timor Tengah Utara, Nusa Tenggara Timur',
  'Kota Kupang, Nusa Tenggara Timur',
  'Kalimantan Barat',
  'Kab. Bengkayang, Kalimantan Barat',
  'Kab. Kapuas Hulu, Kalimantan Barat',
  'Kab. Kayong Utara, Kalimantan Barat',
  'Kab. Ketapang, Kalimantan Barat',
  'Kab. Kubu Raya, Kalimantan Barat',
  'Kab. Landak, Kalimantan Barat',
  'Kab. Melawi, Kalimantan Barat',
  'Kab. Mempawah, Kalimantan Barat',
  'Kab. Sambas, Kalimantan Barat',
  'Kab. Sanggau, Kalimantan Barat',
  'Kab. Sekadau, Kalimantan Barat',
  'Kab. Sintang, Kalimantan Barat',
  'Pontianak, Kalimantan Barat',
  'Singkawang, Kalimantan Barat',
  'Kalimantan Selatan',
  'Kab. Balangan, Kalimantan Selatan',
  'Kab. Banjar, Kalimantan Selatan',
  'Kab. Barto Kuala, Kalimantan Selatan',
  'Kab. Hulu Sungai Selatan, Kalimantan Selatan',
  'Kab. Hulu Sungai Tengah, Kalimantan Selatan',
  'Kab. Hulu Sungai Utara, Kalimantan Selatan',
  'Kab. Kotabaru, Kalimantan Selatan',
  'Kab. Tabalong, Kalimantan Selatan',
  'Kab. Tanah Bumbu, Kalimantan Selatan',
  'Kab. Tanah Laut, Kalimantan Selatan',
  'Kab. Tapin, Kalimantan Selatan',
  'Banjarbaru, Kalimantan Selatan',
  'Banjarmasin, Kalimantan Selatan',
  'Kalimantan Tengah',
  'Kab. Barito Selatan, Kalimantan Tengah',
  'Kab. Barito Timur, Kalimantan Tengah',
  'Kab. Barito Utara, Kalimantan Tengah',
  'Kab. Gunung Mas, Kalimantan Tengah',
  'Kab. Kapuas, Kalimantan Tengah',
  'Kab. Katingan, Kalimantan Tengah',
  'Kab. Kotawaringin Barat, Kalimantan Tengah',
  'Kab. Kotawaringin Timur, Kalimantan Tengah',
  'Kab. Lamandau, Kalimantan Tengah',
  'Kab. Murung Raya, Kalimantan Tengah',
  'Kab. Pulang Pisau, Kalimantan Tengah',
  'Kab. Sukamara, Kalimantan Tengah',
  'Kab. Seruyan, Kalimantan Tengah',
  'Palangka Raya, Kalimantan Tengah',
  'Kalimantan Timur',
  'Kab. Berau, Kalimantan Timur',
  'Kab. Kutai Barat, Kalimantan Timur',
  'Kab. Kutai Kartanegara, Kalimantan Timur',
  'Kab. Kutai Timur, Kalimantan Timur',
  'Kab. Mahakam Ulu, Kalimantan Timur',
  'Kab. Paser, Kalimantan Timur',
  'Kab. Penajam Paser Utara, Kalimantan Timur',
  'Kab. Balikpapan, Kalimantan Timur',
  'Bontang, Kalimantan Timur',
  'Samarinda, Kalimantan Timur',
  'Kalimantan Utara',
  'Kab. Bulungan, Kalimantan Utara',
  'Kab. Malinau, Kalimantan Utara',
  'Kab. Nunukan, Kalimantan Utara',
  'Kab. Tana Tidung, Kalimantan Utara',
  'Tarakan, Kalimantan Utara',
  'Gorontalo',
  'Kab. Bolaemo, Gorontalo',
  'Kab. Bone Bolango, Gorontalo',
  'Kab. Gorontalo, Gorontalo',
  'Kab. Gorontalo Utara, Gorontalo',
  'Kab. Pohuwato, Gorontalo',
  'Kota Gorontalo, Gorontalo',
  'Sulawesi Barat',
  'Kab. Majene, Sulawesi Barat',
  'Kab. Mamasa, Sulawesi Barat',
  'Kab. Mamuju, Sulawesi Barat',
  'Kab. Mamuju Tengah, Sulawesi Barat',
  'Kab. Pasangkayu, Sulawesi Barat',
  'Kab. Polewali Mandar, Sulawesi Barat',
  'Sulawesi Selatan',
  'Kab. Bantaeng, Sulawesi Selatan',
  'Kab. Barru, Sulawesi Selatan',
  'Kab. Bone, Sulawesi Selatan',
  'Kab. Bolukumba, Sulawesi Selatan',
  'Kab. Enrekang, Sulawesi Selatan',
  'Kab. Gowa, Sulawesi Selatan',
  'Kab. Jeneponto, Sulawesi Selatan',
  'Kab. Kepulauan Selayar, Sulawesi Selatan',
  'Kab. Luwu, Sulawesi Selatan',
  'Kab. Luwu Timur, Sulawesi Selatan',
  'Kab. Luwu Utara, Sulawesi Selatan',
  'Kab. Maros, Sulawesi Selatan',
  'Kab. Pangkajene, Sulawesi Selatan',
  'Kab. Pinrang, Sulawesi Selatan',
  'Kab. Sidenreng Rappang, Sulawesi Selatan',
  'Kab. Sinjai, Sulawesi Selatan',
  'Kab. Soppeng, Sulawesi Selatan',
  'Kab. Takalar, Sulawesi Selatan',
  'Kab. Tana Toraja, Sulawesi Selatan',
  'Kab. Wajo, Sulawesi Selatan',
  'Makassar, Sulawesi Selatan',
  'Palopo, Sulawesi Selatan',
  'Parepare Sulawesi Selatan',
  'Sulawesi Tenggara',
  'Kab. Bombana, Sulawesi Tenggara',
  'Kab. Buton, Sulawesi Tenggara',
  'Kab. Buton Selatan, Sulawesi Tenggara',
  'Kab. Buton Tengah, Sulawesi Tenggara',
  'Kab. Buton Utara, Sulawesi Tenggara',
  'Kab. Kolaka, Sulawesi Tenggara',
  'Kab. Kolaka Timur, Sulawesi Tenggara',
  'Kab. Kolaka Utara, Sulawesi Tenggara',
  'Kab. Konawe, Sulawesi Tenggara',
  'Kab. Konawe Kepulauan, Sulawesi Tenggara',
  'Kab. Konawe Selatan, Sulawesi Tenggara',
  'Kab. Konawe Utara, Sulawesi Tenggara',
  'Kab. Muna, Sulawesi Tenggara',
  'Kab. Muna Barat, Sulawesi Tenggara',
  'Kab. Wakatobi, Sulawesi Tenggara',
  'Baubau, Sulawesi Tenggara',
  'Kendari, Sulawesi Tenggara',
  'Sulawesi Tengah',
  'Kab. Banggai, Sulawesi Tengah',
  'Kab. Banggai Kepulauan, Sulawesi Tengah',
  'Kab. Banggai Laut, Sulawesi Tengah',
  'Kab. Buol, Sulawesi Tengah',
  'Kab. Donggala, Sulawesi Tengah',
  'Kab. Morowali, Sulawesi Tengah',
  'Kab. Morowali Utara, Sulawesi Tengah',
  'Kab. Parigi Moutong, Sulawesi Tengah',
  'Kab. Poso, Sulawesi Tengah',
  'Kab. Sigi, Sulawesi Tengah',
  'Kab. Tojo Una-Una, Sulawesi Tengah',
  'Kab. Tolitoli, Sulawesi Tengah',
  'Palu, Sulawesi Tengah',
  'Sulawesi Utara',
  'Kab. Bolaang Mongondow, Sulawesi Utara',
  'Kab. Bolaang Mongondow Selatan, Sulawesi Utara',
  'Kab. Bolaang Mongondow Timur, Sulawesi Utara',
  'Kab. Bolaang Mongondow Utara, Sulawesi Utara',
  'Kab. Kepulauan Sangihe, Sulawesi Utara',
  'Kab. Kepulauan Siau Tagulandang Biaro, Sulawesi Utara',
  'Kab. Kepulauan Talaud, Sulawesi Utara',
  'Kab. Minahasa, Sulawesi Utara',
  'Kab. Minahasa Selatan, Sulawesi Utara',
  'Kab. Minahasa Tenggara, Sulawesi Utara',
  'Kab. Minahasa Utara, Sulawesi Utara',
  'Bitung, Sulawesi Utara',
  'Kotamobagu, Sulawesi Utara',
  'Manado, Sulawesi Utara',
  'Tomohon, Sulawesi Utara',
  'Maluku',
  'Kab. Buru, Maluku',
  'Kab. Buru Selatan, Maluku',
  'Kab. Kepulauan Aru, Maluku',
  'Kab. Kepulauan Tanimbar, Maluku',
  'Kab. Maluku Barat Daya, Maluku',
  'Kab. Maluku Tengah, Maluku',
  'Kab. Maluku Tenggara, Maluku',
  'Kab. Seram Bagian Barat, Maluku',
  'Kab. Seram Bagian Timur, Maluku',
  'Ambon, Maluku',
  'Tual, Maluku',
  'Maluku Utara',
  'Kab. Halmahera Barat, Maluku Utara',
  'Kab. Halmahera Tengah, Maluku Utara',
  'Kab. Halmahera Timur, Maluku Utara',
  'Kab. Halmahera Selatan, Maluku Utara',
  'Kab. Halmahera Utara, Maluku Utara',
  'Kab. Kepulauan Sula, Maluku Utara',
  'Kab. Pulau Morotai, Maluku Utara',
  'Kab. Pulau Tailabu, Maluku Utara',
  'Ternate, Maluku Utara',
  'Tidore Kepulauan, Maluku Utara',
  'Papua',
  'Kab. Asmat, Papua',
  'Kab. Biak Numfor, Papua',
  'Kab. Boven Digoel, Papua',
  'Kab. Deiyai, Papua',
  'Kab. Dogiyai, Papua',
  'Kab. Intan Jaya, Papua',
  'Kab. Jayapura, Papua',
  'Kab. Jayawijaya, Papua',
  'Kab. Keerom, Papua',
  'Kab. Kepulauan Yapen, Papua',
  'Kab. Lanny Jaya, Papua',
  'Kab. Mamberamo Raya, Papua',
  'Kab. Mappi, Papua',
  'Kab. Merauke, Papua',
  'Kab. Mimika, Papua',
  'Kab. Nabire, Papua',
  'Kab. Nduga, Papua',
  'Kab. Paniai, Papua',
  'Kab. Pegunungan Bintang, Papua',
  'Kab. Puncak, Papua',
  'Kab. Puncak Jaya, Papua',
  'Kab. Sarmi, Papua',
  'Kab. Supiori, Papua',
  'Kab. Tolikara, Papua',
  'Kab. Waropen, Papua',
  'Kab. Yahukimo, Papua',
  'Kab. Yalimo, Papua',
  'Kota Jayapura, Papua',
  'Papua Barat',
  'Kab. Fakfak, Papua Barat',
  'Kab. Kaimana, Papua Barat',
  'Kab. Manokwari, Papua Barat',
  'Kab. Manokwari Selatan, Papua Barat',
  'Kab. Maybrat, Papua Barat',
  'Kab. Pegunungan Arfak, Papua Barat',
  'Kab. Raja Ampat, Papua Barat',
  'Kab. Sorong, Papua Barat',
  'Kab. Sorong Selatan, Papua Barat',
  'Kab. Tambrauw, Papua Barat',
  'Kab. Teluk Bintuni, Papua Barat',
  'Kab. Teluk Wondama, Papua Barat',
  'Kota Sorong, Papua Barat'
])

export default cities
